import { CategoryGroup, Product, RecentOrder } from './product';

export const categoryGroups: CategoryGroup[] = [
  {
    name: 'Ethnic Wear',
    description: 'Sarees, kurtis, salwar sets, and lehengas for festive days.',
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=900&q=80',
    children: ['Sarees', 'Kurtis', 'Salwar Sets', 'Lehengas']
  },
  {
    name: 'Western Wear',
    description: 'Dresses, tops, shirts, jeans, trousers, and skirts.',
    image: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=80',
    children: ['Dresses', 'Tops', 'Shirts', 'Jeans', 'Trousers', 'Skirts']
  },
  {
    name: 'Party Wear',
    description: 'Gowns, party dresses, and designer collections.',
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=900&q=80',
    children: ['Gowns', 'Party Dresses', 'Designer Collections']
  },
  {
    name: 'Active Wear',
    description: 'Gym wear, leggings, and sports tops.',
    image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=900&q=80',
    children: ['Gym Wear', 'Leggings', 'Sports Tops']
  },
  {
    name: 'Night Wear',
    description: 'Night suits and sleepwear for easy comfort.',
    image: 'https://images.unsplash.com/photo-1534126511673-b6899657816a?auto=format&fit=crop&w=900&q=80',
    children: ['Night Suits', 'Sleepwear']
  },
  {
    name: 'Accessories',
    description: 'Handbags, scarves, and jewellery to complete each look.',
    image: 'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=900&q=80',
    children: ['Handbags', 'Scarves', 'Jewellery', 'Hair Accessories']
  }
];

export const products: Product[] = [
  {
    id: 1,
    name: 'Rose Silk Saree',
    category: 'Ethnic Wear',
    subCategory: 'Sarees',
    price: 4999,
    discountPrice: 3899,
    rating: 4.8,
    sold: 184,
    stock: 18,
    sizes: ['Free Size'],
    colors: ['Rose', 'Gold', 'Maroon'],
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=900&q=80',
    badges: ['Festive', '20% Off'],
    description: 'Soft silk blend saree with a light zari border and ready-to-style drape.',
    isNew: true,
    isBestSeller: true
  },
  {
    id: 2,
    name: 'Cotton Printed Kurti',
    category: 'Ethnic Wear',
    subCategory: 'Kurtis',
    price: 1799,
    discountPrice: 1299,
    rating: 4.6,
    sold: 96,
    stock: 34,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Teal', 'White', 'Mustard'],
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Indian_woman_wearing_a_kurti.jpg?width=900',
    badges: ['Daily Wear'],
    description: 'Breathable cotton kurti with side pockets and a clean straight fit.',
    isNew: false,
    isBestSeller: true
  },
  {
    id: 3,
    name: 'Ivory Salwar Set',
    category: 'Ethnic Wear',
    subCategory: 'Salwar Sets',
    price: 2899,
    discountPrice: 2299,
    rating: 4.5,
    sold: 72,
    stock: 20,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Ivory', 'Peach', 'Mint'],
    image: 'https://images.unsplash.com/photo-1502716119720-b23a93e5fe1b?auto=format&fit=crop&w=900&q=80',
    badges: ['Comfort Fit'],
    description: 'Coordinated kurta, salwar, and dupatta set for workdays and family events.',
    isNew: true,
    isBestSeller: false
  },
  {
    id: 4,
    name: 'Embroidered Lehenga',
    category: 'Ethnic Wear',
    subCategory: 'Lehengas',
    price: 8999,
    discountPrice: 6999,
    rating: 4.9,
    sold: 41,
    stock: 9,
    sizes: ['S', 'M', 'L'],
    colors: ['Wine', 'Navy', 'Emerald'],
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/A_flared_lehenga.jpg?width=900',
    badges: ['Wedding Edit'],
    description: 'Statement lehenga with detailed embroidery, dupatta, and structured blouse.',
    isNew: true,
    isBestSeller: false
  },
  {
    id: 5,
    name: 'Midi Wrap Dress',
    category: 'Western Wear',
    subCategory: 'Dresses',
    price: 2499,
    discountPrice: 1899,
    rating: 4.7,
    sold: 138,
    stock: 27,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Coral', 'Black', 'Sage'],
    image: 'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?auto=format&fit=crop&w=900&q=80',
    badges: ['New Arrival'],
    description: 'Flattering wrap dress with a soft waist tie and easy day-to-night styling.',
    isNew: true,
    isBestSeller: true
  },
  {
    id: 6,
    name: 'Linen Office Shirt',
    category: 'Western Wear',
    subCategory: 'Shirts',
    price: 1599,
    discountPrice: 1199,
    rating: 4.4,
    sold: 87,
    stock: 42,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['White', 'Sky', 'Olive'],
    image: 'https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=900&q=80',
    badges: ['Workwear'],
    description: 'Relaxed linen shirt with a crisp collar and breathable finish.',
    isNew: false,
    isBestSeller: false
  },
  {
    id: 7,
    name: 'High Rise Straight Jeans',
    category: 'Western Wear',
    subCategory: 'Jeans',
    price: 2999,
    discountPrice: 2399,
    rating: 4.6,
    sold: 156,
    stock: 30,
    sizes: ['26', '28', '30', '32', '34'],
    colors: ['Indigo', 'Black', 'Light Blue'],
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=900&q=80',
    badges: ['Best Seller'],
    description: 'High rise jeans with a straight leg, soft stretch, and ankle-length finish.',
    isNew: false,
    isBestSeller: true
  },
  {
    id: 8,
    name: 'Satin Party Gown',
    category: 'Party Wear',
    subCategory: 'Gowns',
    price: 6999,
    discountPrice: 5499,
    rating: 4.8,
    sold: 68,
    stock: 12,
    sizes: ['S', 'M', 'L'],
    colors: ['Emerald', 'Black', 'Champagne'],
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=900&q=80',
    badges: ['Party Edit'],
    description: 'Fluid satin gown with a graceful neckline and subtle side slit.',
    isNew: true,
    isBestSeller: true
  },
  {
    id: 9,
    name: 'Training Leggings',
    category: 'Active Wear',
    subCategory: 'Leggings',
    price: 1999,
    discountPrice: 1499,
    rating: 4.5,
    sold: 103,
    stock: 51,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black', 'Plum', 'Teal'],
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Female_leggings.jpg?width=900',
    badges: ['4-Way Stretch'],
    description: 'High support leggings with stretch fabric, quick dry finish, and side pocket.',
    isNew: false,
    isBestSeller: false
  },
  {
    id: 10,
    name: 'Soft Night Suit',
    category: 'Night Wear',
    subCategory: 'Night Suits',
    price: 1899,
    discountPrice: 1399,
    rating: 4.7,
    sold: 91,
    stock: 39,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Lavender', 'Grey', 'Peach'],
    image: 'https://images.unsplash.com/photo-1612336307429-8a898d10e223?auto=format&fit=crop&w=900&q=80',
    badges: ['Soft Touch'],
    description: 'Two-piece night suit in gentle fabric with a relaxed, sleep-friendly fit.',
    isNew: false,
    isBestSeller: true
  },
  {
    id: 11,
    name: 'Quilted Handbag',
    category: 'Accessories',
    subCategory: 'Handbags',
    price: 2299,
    discountPrice: 1699,
    rating: 4.3,
    sold: 59,
    stock: 25,
    sizes: ['One Size'],
    colors: ['Tan', 'Black', 'Cherry'],
    image: 'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=900&q=80',
    badges: ['Accessory'],
    description: 'Compact quilted handbag with chain strap and secure inner pocket.',
    isNew: true,
    isBestSeller: false
  },
  {
    id: 12,
    name: 'Designer Scarf',
    category: 'Accessories',
    subCategory: 'Scarves',
    price: 999,
    discountPrice: 749,
    rating: 4.4,
    sold: 112,
    stock: 64,
    sizes: ['One Size'],
    colors: ['Blush', 'Navy', 'Cream'],
    image: 'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?auto=format&fit=crop&w=900&q=80',
    badges: ['Gift Pick'],
    description: 'Light printed scarf that works with kurtis, dresses, and office layers.',
    isNew: false,
    isBestSeller: false
  },
  {
    id: 13,
    name: 'Pearl Drop Earrings',
    category: 'Accessories',
    subCategory: 'Jewellery',
    price: 1299,
    discountPrice: 899,
    rating: 4.6,
    sold: 124,
    stock: 58,
    sizes: ['One Size'],
    colors: ['Pearl', 'Gold', 'Silver'],
    image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=900&q=80',
    badges: ['Jewellery', 'Gift Pick'],
    description: 'Elegant pearl drop earrings with a lightweight finish for daily and occasion wear.',
    isNew: true,
    isBestSeller: true
  },
  {
    id: 14,
    name: 'Layered Gold Necklace',
    category: 'Accessories',
    subCategory: 'Jewellery',
    price: 1899,
    discountPrice: 1399,
    rating: 4.5,
    sold: 88,
    stock: 36,
    sizes: ['One Size'],
    colors: ['Gold', 'Rose Gold'],
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=900&q=80',
    badges: ['Layered Look'],
    description: 'Polished layered necklace that adds a refined accent to dresses, shirts, and sarees.',
    isNew: true,
    isBestSeller: false
  },
  {
    id: 15,
    name: 'Structured Tote Bag',
    category: 'Accessories',
    subCategory: 'Handbags',
    price: 3299,
    discountPrice: 2499,
    rating: 4.7,
    sold: 76,
    stock: 22,
    sizes: ['One Size'],
    colors: ['Tan', 'Black', 'Ivory'],
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=80',
    badges: ['Work Bag'],
    description: 'Roomy structured tote with polished handles, zip closure, and everyday storage.',
    isNew: true,
    isBestSeller: true
  },
  {
    id: 16,
    name: 'Mini Shoulder Bag',
    category: 'Accessories',
    subCategory: 'Handbags',
    price: 2199,
    discountPrice: 1599,
    rating: 4.4,
    sold: 63,
    stock: 31,
    sizes: ['One Size'],
    colors: ['Pink', 'Black', 'Beige'],
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80',
    badges: ['Party Carry'],
    description: 'Compact shoulder bag for evenings, brunch plans, and lightweight essentials.',
    isNew: false,
    isBestSeller: false
  },
  {
    id: 17,
    name: 'Silk Square Scarf',
    category: 'Accessories',
    subCategory: 'Scarves',
    price: 1499,
    discountPrice: 1099,
    rating: 4.5,
    sold: 97,
    stock: 44,
    sizes: ['One Size'],
    colors: ['Blush', 'Emerald', 'Navy'],
    image: 'https://images.unsplash.com/photo-1601924638867-3ec9d3a9e721?auto=format&fit=crop&w=900&q=80',
    badges: ['Silk Feel'],
    description: 'Smooth square scarf that can be styled around the neck, bag handle, or hair.',
    isNew: true,
    isBestSeller: false
  },
  {
    id: 18,
    name: 'Pearl Hair Clip Set',
    category: 'Accessories',
    subCategory: 'Hair Accessories',
    price: 899,
    discountPrice: 599,
    rating: 4.3,
    sold: 142,
    stock: 70,
    sizes: ['One Size'],
    colors: ['Pearl', 'Gold'],
    image: 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=900&q=80',
    badges: ['Accessory Set'],
    description: 'Set of pearl-accent hair clips to finish soft curls, buns, and festive styles.',
    isNew: false,
    isBestSeller: true
  },
  {
    id: 19,
    name: 'Pleated Midi Skirt',
    category: 'Western Wear',
    subCategory: 'Skirts',
    price: 2299,
    discountPrice: 1699,
    rating: 4.6,
    sold: 81,
    stock: 29,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Champagne', 'Black', 'Wine'],
    image: 'https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?auto=format&fit=crop&w=900&q=80',
    badges: ['Easy Styling'],
    description: 'Flowy pleated midi skirt with a comfortable waist and polished movement.',
    isNew: true,
    isBestSeller: false
  },
  {
    id: 20,
    name: 'Denim Shirt Dress',
    category: 'Western Wear',
    subCategory: 'Dresses',
    price: 2799,
    discountPrice: 2199,
    rating: 4.5,
    sold: 92,
    stock: 33,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Mid Blue', 'Dark Blue'],
    image: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=80',
    badges: ['Weekend Fit'],
    description: 'Button-front denim dress with a flattering belt and casual daywear finish.',
    isNew: false,
    isBestSeller: true
  },
  {
    id: 21,
    name: 'Floral Co-ord Set',
    category: 'Western Wear',
    subCategory: 'Tops',
    price: 3199,
    discountPrice: 2499,
    rating: 4.7,
    sold: 74,
    stock: 26,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Ivory', 'Pink', 'Sage'],
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80',
    badges: ['Co-ord'],
    description: 'Fresh floral co-ord set with a tailored top and relaxed matching bottom.',
    isNew: true,
    isBestSeller: false
  },
  {
    id: 22,
    name: 'Handloom Palazzo Set',
    category: 'Ethnic Wear',
    subCategory: 'Salwar Sets',
    price: 3499,
    discountPrice: 2699,
    rating: 4.6,
    sold: 67,
    stock: 24,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Indigo', 'Rust', 'Cream'],
    image: 'https://images.unsplash.com/photo-1583391733956-6c78276477e2?auto=format&fit=crop&w=900&q=80',
    badges: ['Handloom'],
    description: 'Handloom-inspired kurta and palazzo set with a soft dupatta for graceful comfort.',
    isNew: true,
    isBestSeller: false
  },
  {
    id: 23,
    name: 'Velvet Party Dress',
    category: 'Party Wear',
    subCategory: 'Party Dresses',
    price: 4499,
    discountPrice: 3499,
    rating: 4.8,
    sold: 105,
    stock: 19,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Wine', 'Black', 'Emerald'],
    image: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=900&q=80',
    badges: ['Night Out'],
    description: 'Rich velvet party dress with a sleek fit and soft shine for evening plans.',
    isNew: false,
    isBestSeller: true
  },
  {
    id: 24,
    name: 'Satin Sleep Set',
    category: 'Night Wear',
    subCategory: 'Sleepwear',
    price: 2499,
    discountPrice: 1799,
    rating: 4.5,
    sold: 83,
    stock: 37,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Champagne', 'Lavender', 'Rose'],
    image: 'https://images.unsplash.com/photo-1612336307429-8a898d10e223?auto=format&fit=crop&w=900&q=80',
    badges: ['Sleep Edit'],
    description: 'Smooth satin sleep set with a relaxed cut and elegant bedtime comfort.',
    isNew: true,
    isBestSeller: false
  }
];

export const recentOrders: RecentOrder[] = [
  { id: 'ORD-1028', customer: 'Priya Sharma', total: 7798, status: 'Shipped', date: '08 Jun 2026' },
  { id: 'ORD-1027', customer: 'Anika Mehta', total: 2399, status: 'Packed', date: '08 Jun 2026' },
  { id: 'ORD-1026', customer: 'Sneha Patel', total: 5499, status: 'Delivered', date: '07 Jun 2026' },
  { id: 'ORD-1025', customer: 'Riya Shah', total: 3648, status: 'Delivered', date: '07 Jun 2026' }
];
