import { CategoryGroup, Product, RecentOrder } from './product';

export const categoryGroups: CategoryGroup[] = [
  {
    name: 'Ethnic Wear',
    description: 'Sarees, kurtis, salwar sets, and lehengas for festive days.',
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=900&q=80',
    children: ['Sarees', 'Kurtis', 'Salwar Sets', 'Lehengas']
  },
  {
    name: 'Western Wear',
    description: 'Dresses, tops, shirts, jeans, trousers, and skirts.',
    image: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=80',
    children: ['Dresses', 'Tops', 'Shirts', 'Jeans', 'Trousers', 'Skirts']
  },
  {
    name: 'Party Wear',
    description: 'Gowns, party dresses, and designer collections.',
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=900&q=80',
    children: ['Gowns', 'Party Dresses', 'Designer Collections']
  },
  {
    name: 'Active Wear',
    description: 'Gym wear, leggings, and sports tops.',
    image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=900&q=80',
    children: ['Gym Wear', 'Leggings', 'Sports Tops']
  },
  {
    name: 'Night Wear',
    description: 'Night suits and sleepwear for easy comfort.',
    image: 'https://images.unsplash.com/photo-1534126511673-b6899657816a?auto=format&fit=crop&w=900&q=80',
    children: ['Night Suits', 'Sleepwear']
  },
  {
    name: 'Accessories',
    description: 'Handbags, scarves, and jewellery to complete each look.',
    image: 'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=900&q=80',
    children: ['Handbags', 'Scarves', 'Jewellery']
  }
];

export const products: Product[] = [
  {
    id: 1,
    name: 'Rose Silk Saree',
    category: 'Ethnic Wear',
    subCategory: 'Sarees',
    price: 4999,
    discountPrice: 3899,
    rating: 4.8,
    sold: 184,
    stock: 18,
    sizes: ['Free Size'],
    colors: ['Rose', 'Gold', 'Maroon'],
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=900&q=80',
    badges: ['Festive', '20% Off'],
    description: 'Soft silk blend saree with a light zari border and ready-to-style drape.',
    isNew: true,
    isBestSeller: true
  },
  {
    id: 2,
    name: 'Cotton Printed Kurti',
    category: 'Ethnic Wear',
    subCategory: 'Kurtis',
    price: 1799,
    discountPrice: 1299,
    rating: 4.6,
    sold: 96,
    stock: 34,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Teal', 'White', 'Mustard'],
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Indian_woman_wearing_a_kurti.jpg?width=900',
    badges: ['Daily Wear'],
    description: 'Breathable cotton kurti with side pockets and a clean straight fit.',
    isNew: false,
    isBestSeller: true
  },
  {
    id: 3,
    name: 'Ivory Salwar Set',
    category: 'Ethnic Wear',
    subCategory: 'Salwar Sets',
    price: 2899,
    discountPrice: 2299,
    rating: 4.5,
    sold: 72,
    stock: 20,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Ivory', 'Peach', 'Mint'],
    image: 'https://images.unsplash.com/photo-1502716119720-b23a93e5fe1b?auto=format&fit=crop&w=900&q=80',
    badges: ['Comfort Fit'],
    description: 'Coordinated kurta, salwar, and dupatta set for workdays and family events.',
    isNew: true,
    isBestSeller: false
  },
  {
    id: 4,
    name: 'Embroidered Lehenga',
    category: 'Ethnic Wear',
    subCategory: 'Lehengas',
    price: 8999,
    discountPrice: 6999,
    rating: 4.9,
    sold: 41,
    stock: 9,
    sizes: ['S', 'M', 'L'],
    colors: ['Wine', 'Navy', 'Emerald'],
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/A_flared_lehenga.jpg?width=900',
    badges: ['Wedding Edit'],
    description: 'Statement lehenga with detailed embroidery, dupatta, and structured blouse.',
    isNew: true,
    isBestSeller: false
  },
  {
    id: 5,
    name: 'Midi Wrap Dress',
    category: 'Western Wear',
    subCategory: 'Dresses',
    price: 2499,
    discountPrice: 1899,
    rating: 4.7,
    sold: 138,
    stock: 27,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Coral', 'Black', 'Sage'],
    image: 'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?auto=format&fit=crop&w=900&q=80',
    badges: ['New Arrival'],
    description: 'Flattering wrap dress with a soft waist tie and easy day-to-night styling.',
    isNew: true,
    isBestSeller: true
  },
  {
    id: 6,
    name: 'Linen Office Shirt',
    category: 'Western Wear',
    subCategory: 'Shirts',
    price: 1599,
    discountPrice: 1199,
    rating: 4.4,
    sold: 87,
    stock: 42,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['White', 'Sky', 'Olive'],
    image: 'https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=900&q=80',
    badges: ['Workwear'],
    description: 'Relaxed linen shirt with a crisp collar and breathable finish.',
    isNew: false,
    isBestSeller: false
  },
  {
    id: 7,
    name: 'High Rise Straight Jeans',
    category: 'Western Wear',
    subCategory: 'Jeans',
    price: 2999,
    discountPrice: 2399,
    rating: 4.6,
    sold: 156,
    stock: 30,
    sizes: ['26', '28', '30', '32', '34'],
    colors: ['Indigo', 'Black', 'Light Blue'],
    image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=900&q=80',
    badges: ['Best Seller'],
    description: 'High rise jeans with a straight leg, soft stretch, and ankle-length finish.',
    isNew: false,
    isBestSeller: true
  },
  {
    id: 8,
    name: 'Satin Party Gown',
    category: 'Party Wear',
    subCategory: 'Gowns',
    price: 6999,
    discountPrice: 5499,
    rating: 4.8,
    sold: 68,
    stock: 12,
    sizes: ['S', 'M', 'L'],
    colors: ['Emerald', 'Black', 'Champagne'],
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=900&q=80',
    badges: ['Party Edit'],
    description: 'Fluid satin gown with a graceful neckline and subtle side slit.',
    isNew: true,
    isBestSeller: true
  },
  {
    id: 9,
    name: 'Training Leggings',
    category: 'Active Wear',
    subCategory: 'Leggings',
    price: 1999,
    discountPrice: 1499,
    rating: 4.5,
    sold: 103,
    stock: 51,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Black', 'Plum', 'Teal'],
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Female_leggings.jpg?width=900',
    badges: ['4-Way Stretch'],
    description: 'High support leggings with stretch fabric, quick dry finish, and side pocket.',
    isNew: false,
    isBestSeller: false
  },
  {
    id: 10,
    name: 'Soft Night Suit',
    category: 'Night Wear',
    subCategory: 'Night Suits',
    price: 1899,
    discountPrice: 1399,
    rating: 4.7,
    sold: 91,
    stock: 39,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Lavender', 'Grey', 'Peach'],
    image: 'https://images.unsplash.com/photo-1534126511673-b6899657816a?auto=format&fit=crop&w=900&q=80',
    badges: ['Soft Touch'],
    description: 'Two-piece night suit in gentle fabric with a relaxed, sleep-friendly fit.',
    isNew: false,
    isBestSeller: true
  },
  {
    id: 11,
    name: 'Quilted Handbag',
    category: 'Accessories',
    subCategory: 'Handbags',
    price: 2299,
    discountPrice: 1699,
    rating: 4.3,
    sold: 59,
    stock: 25,
    sizes: ['One Size'],
    colors: ['Tan', 'Black', 'Cherry'],
    image: 'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=900&q=80',
    badges: ['Accessory'],
    description: 'Compact quilted handbag with chain strap and secure inner pocket.',
    isNew: true,
    isBestSeller: false
  },
  {
    id: 12,
    name: 'Designer Scarf',
    category: 'Accessories',
    subCategory: 'Scarves',
    price: 999,
    discountPrice: 749,
    rating: 4.4,
    sold: 112,
    stock: 64,
    sizes: ['One Size'],
    colors: ['Blush', 'Navy', 'Cream'],
    image: 'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?auto=format&fit=crop&w=900&q=80',
    badges: ['Gift Pick'],
    description: 'Light printed scarf that works with kurtis, dresses, and office layers.',
    isNew: false,
    isBestSeller: false
  }
];

export const recentOrders: RecentOrder[] = [
  { id: 'ORD-1028', customer: 'Priya Sharma', total: 7798, status: 'Shipped', date: '08 Jun 2026' },
  { id: 'ORD-1027', customer: 'Anika Mehta', total: 2399, status: 'Packed', date: '08 Jun 2026' },
  { id: 'ORD-1026', customer: 'Sneha Patel', total: 5499, status: 'Delivered', date: '07 Jun 2026' },
  { id: 'ORD-1025', customer: 'Riya Shah', total: 3648, status: 'Delivered', date: '07 Jun 2026' }
];
